# Production Profile Configuration

# Enable caching
spring.thymeleaf.cache=true

# Disable SQL logging
spring.jpa.show-sql=false

# Secure cookies
server.servlet.session.cookie.secure=true

# Logging
logging.level.root=WARN
logging.level.com.uacb=INFO

# Database
spring.jpa.hibernate.ddl-auto=update
